In [13]:
#Load the necessory packages and libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
eeg_data = pd.read_csv("eeg_features")

In [15]:
eeg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 21 columns):
Activity                             11500 non-null float64
Mobility                             11500 non-null float64
Complexity                           11500 non-null float64
Kurtosis                             11500 non-null float64
2nd Difference Mean                  11500 non-null float64
2nd Difference Max                   11500 non-null float64
Coeffiecient of Variation            11500 non-null float64
Skewness                             11500 non-null float64
1st Difference Mean                  11500 non-null float64
1st Difference Max                   11500 non-null float64
Wavelet Approximate Mean             11500 non-null float64
Wavelet Approximate Std Deviation    11500 non-null float64
Wavelet Detailed Mean                11500 non-null float64
Wavelet Detailed Std Deviation       11500 non-null float64
Wavelet Approximate Energy           11500 non-null

In [16]:
eeg_X = eeg_data.drop('y',axis=1)
eeg_Y = eeg_data['y']

In [17]:
#standardization
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [19]:
scaler.fit(eeg_X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [20]:
scaled_features = scaler.transform(eeg_X)

In [21]:
eeg_feature = pd.DataFrame(scaled_features)
eeg_feature.head()

0         1         2         3         4         5         6   \
0 -0.222864  0.077247 -0.139909 -0.590682  0.083719  0.193719  0.002680   
1  2.567363 -1.235215  1.477894 -0.532721  2.953272  2.667414  0.031063   
2 -0.326074  0.301299  0.387987 -1.013345 -0.374289 -0.263437  0.003399   
3 -0.337842  0.162652  0.933090  2.539759 -0.521943 -0.166927  0.004779   
4 -0.316347 -0.776756 -0.219714 -0.110022 -0.377606 -0.155330  0.018692   

         7         8         9         10        11        12        13  \
0  0.428616  0.017762  0.043959 -0.640038  0.041128 -0.252944 -0.079321   
1  0.573445  2.397372  2.114061  0.648986  2.730659 -3.570428  2.827618   
2  0.027148 -0.332939 -0.481745 -0.246860 -0.431978  1.012732 -0.407652   
3 -2.711158 -0.509974 -0.288645 -0.277415 -0.477932  0.489424 -0.469083   
4  0.216540 -0.384455 -0.370573  0.299761 -0.250972 -0.366760 -0.417572   

         14        15        16        17        18        19  
0 -0.204336 -0.244402 -0.262383 -0.269385 -0.121941 -0.208735  
1  2.281329  2.551466  2.374573  2.115570  0.000913  1.913398  
2 -0.331757 -0.313125 -0.273664 -0.271567 -0.200953 -0.314402  
3 -0.338409 -0.331251 -0.264505 -0.256596  0.003267 -0.315614  
4 -0.295610 -0.324277 -0.267266 -0.264462  0.006699 -0.321871

## Univariate Selection

In [22]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [24]:
# feature selection
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(eeg_X, eeg_Y)

In [27]:
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(eeg_X)

[1.157e+03 2.129e+00 8.057e-03 3.427e+01 1.222e+03 3.635e+01 5.200e-05
 9.766e-02 1.262e+03 9.944e+02 1.355e-01 1.333e+03 1.267e-02 1.245e+03
 1.200e+03 1.018e+03 8.514e+02 7.730e+02 3.470e-04 1.021e+03]


In [28]:
# summarize selected features
print(features[0:5,:])

[[0.11  0.101 0.115 0.092]
 [0.492 0.42  0.505 0.491]
 [0.049 0.054 0.046 0.047]
 [0.029 0.03  0.04  0.039]
 [0.048 0.047 0.073 0.046]]


In [29]:
features.shape

(11500, 4)

## Recursive Feature Elimination

In [30]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# feature selection
model = RandomForestClassifier(n_estimators=100)
rfe = RFE(model, 3)
fit = rfe.fit(eeg_X, eeg_Y)
print("Num Features: ") 
print(fit.n_features_)
print("Selected Features:")
print(fit.support_)
print("Feature Ranking:")
print(fit.ranking_)